<?php
include '../auth/admin-check.php';
include '../config/db.php';

$result = $conn->query("SELECT * FROM trip_plans WHERE status = 'Current' ORDER BY id DESC");

$totalCurrent = 0;
if ($result) {
    $totalCurrent = $result->num_rows;
}

$adminPageTitle = "Current Travel Plans";
$adminCurrentPage = "current-plans";
include 'includes/admin-header.php';
?>

<div class="admin-page-wrap">
  <div class="admin-page-hero mb-4">
    <div>
      <h1 class="admin-page-title mb-2">Current Travel Plans</h1>
      <p class="admin-page-subtitle mb-0">
        View and manage all currently active travel plans generated by users.
      </p>
    </div>
  </div>

  <div class="row g-4 mb-4">
    <div class="col-md-6 col-xl-4">
      <div class="admin-summary-card">
        <span class="admin-summary-label">Active Plans</span>
        <h3><?php echo $totalCurrent; ?></h3>
        <p>Currently available travel plans</p>
      </div>
    </div>

    <div class="col-md-6 col-xl-4">
      <div class="admin-summary-card">
        <span class="admin-summary-label">Status</span>
        <h3>Live</h3>
        <p>Plans waiting to be completed</p>
      </div>
    </div>

    <div class="col-md-12 col-xl-4">
      <div class="admin-summary-card">
        <span class="admin-summary-label">Management</span>
        <h3>Admin</h3>
        <p>Review, monitor, and update trip status</p>
      </div>
    </div>
  </div>

  <div class="admin-table-card">
    <div class="admin-table-head">
      <div>
        <h4>Current Plan Records</h4>
        <p>All travel plans with status marked as Current.</p>
      </div>
    </div>

    <div class="table-responsive">
      <table class="table admin-modern-table align-middle mb-0">
        <thead>
          <tr>
            <th>ID</th>
            <th>User</th>
            <th>Start Point</th>
            <th>Start Time</th>
            <th>Trip Type</th>
            <th>Selected Places</th>
            <th>Total Distance</th>
            <th>Date</th>
            <th class="text-center">Action</th>
          </tr>
        </thead>
        <tbody>
          <?php if ($result && $result->num_rows > 0): ?>
            <?php while ($row = $result->fetch_assoc()): ?>
              <tr>
                <td>#<?php echo $row['id']; ?></td>
                <td><?php echo htmlspecialchars($row['user_name']); ?></td>
                <td><?php echo htmlspecialchars($row['start_point']); ?></td>
                <td><?php echo htmlspecialchars($row['start_time']); ?></td>
                <td><?php echo htmlspecialchars($row['trip_type']); ?></td>
                <td><?php echo htmlspecialchars($row['selected_places']); ?></td>
                <td><?php echo htmlspecialchars($row['total_distance']); ?> km</td>
                <td><?php echo htmlspecialchars($row['created_at']); ?></td>
                <td class="text-center">
                  <a href="complete-plan.php?id=<?php echo $row['id']; ?>" class="btn btn-main btn-sm admin-action-btn">
                    Mark Completed
                  </a>
                </td>
              </tr>
            <?php endwhile; ?>
          <?php else: ?>
            <tr>
              <td colspan="9" class="text-center py-5 text-muted" style="height : 180px;">
                No current travel plans found.
              </td>
            </tr>
          <?php endif; ?>
        </tbody>
      </table>
    </div>
  </div>
</div>

<?php include 'includes/admin-footer.php'; ?>